version: '2'
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:@postgres/api_dev
      TEST_DATABASE_URL: postgres://postgres:@postgres/api_test
    depends_on:
      - postgres
    volumes:
      - ./api/:/app
    command: mix phx.server
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
