version: '2'
services:
  api:
    build: ./api
    ports:
      - "8080:4000"
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:5490@postgres/api_dev
      TEST_DATABASE_URL: postgres://postgres:5490@postgres/api_test
    depends_on:
      - postgres
    volumes:
      - ./api/:/app
    command: mix phx.server
  client:
    build: ./client
    depends_on:
      - api
    environment:
      API_BASE_URL: http://localhost:8080
    image: node:7.8.0
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: bash -c "yarn && yarn start"
  postgres:
    image: postgres:9.5
    ports:
      - "5490:5432"
